# Generated by Django 2.0.13 on 2019-05-09 03:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_auto_20190509_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('company_name', models.CharField(blank=True, max_length=256, verbose_name='Company name')),
                ('address', models.CharField(blank=True, max_length=512, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Address')),
                ('email', models.CharField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Embarcador',
                'verbose_name_plural': 'Embarcadores',
            },
        ),
        migrations.CreateModel(
            name='ShipperRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CatalogCategory', verbose_name='Category')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CatalogRequirement', verbose_name='Requirement')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shippers.Shipper', verbose_name='Shipper')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
            },
        ),
    ]
