# Generated by Django 2.0.13 on 2019-05-09 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='shipperrequirement',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.CatalogCategory', verbose_name='Category Requirement'),
        ),
    ]
