# Generated by Django 2.0.13 on 2019-05-09 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0003_auto_20190509_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipperrequirement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.CatalogCategory', verbose_name='Category Requirement'),
        ),
        migrations.AlterField(
            model_name='shipperrequirement',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.CatalogRequirement', verbose_name='Requirement'),
        ),
        migrations.AlterField(
            model_name='shipperrequirement',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shippers.Shipper', verbose_name='Shipper'),
        ),
    ]
