# Generated by Django 2.0.13 on 2019-05-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0004_auto_20190509_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='num_requirements',
            field=models.IntegerField(default=0, verbose_name='Num requirements'),
        ),
    ]
