# Generated by Django 2.0.13 on 2019-05-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='status',
            field=models.CharField(blank=True, choices=[('VALIDATION_IN_PROCCESS', 'Validation in proccess'), ('VALIDATED', 'Validated'), ('SUSPENDED', 'Suspended')], default='VALIDATION_IN_PROCCESS', max_length=254, verbose_name='Status'),
        ),
    ]
