# Generated by Django 2.0.13 on 2019-05-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0004_auto_20190509_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, max_length=8, verbose_name='Licence plate'),
        ),
    ]
