# Generated by Django 2.0.13 on 2019-05-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0005_auto_20190509_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('0', 'Sin especificar'), ('1', 'Camioneta de 1.5 toneladas'), ('2', 'Camioneta de 3.5 toneladas'), ('3', 'Camioneta de 5.5 toneladas'), ('4', 'Rabón con caja seca'), ('5', 'Rabón con caja refrigeradaTorton con caja seca'), ('6', 'Torton con caja refrigerada'), ('7', 'Trailer de 48ft con caja seca'), ('8', 'Trailer de 48ft con caja refrigerada'), ('9', 'Trailer de 53ft con caja seca'), ('10', 'Trailer de 53ft con caja refrigerada')], max_length=1, verbose_name='Type vehicle'),
        ),
    ]
